### ISSUE TITLE
Better alignment in the form's header

### ISSUE THREAD

**Issue by rammazzoti2000** [Mupa1/HTML-Forms#4]
The header's paragraph in the form could have the same right and left alignment with the input and label elements, so for that you could either increase the font-size of paragraph or decrease the overall width of the form container.

**Comment by Mupa1** [comment]
Hi @rammazzoti2000 thanks for the feedback, but in the original form, the header's p is aligned center, not right and left as you are suggesting

**Comment by rammazzoti2000** [comment]
Hello @Mupa1,
I used left and right terms to give a better reference between header's paragraph and the form (I know it is centered), and your page looks identical with the original.

I was suggesting that if you try to make the width of input match the width of header's paragraph it would look better then the original, that's it.

I tried to change the width of `main` tag to 364px, and the the margin of `.privacy-text` class to 30px and it looks better then the original, that'all.
